baseURL = "https://signalsandsilence.com/"
languageCode = "en-us"
title = "Signals & Silence"
theme = "PaperMod"

[params]
  ShowToc = true
  ShowBreadCrumbs = true
  defaultTheme = "light"
  disableSpecial1stPost = true
  ShowSearch = true
  customCSS = ["css/custom.css"]
  comments = true
  [params.giscus]
    repo = "harshavardhanab/signalsandsilence"
    repoID = "R_kgDOPN9Pmw"                  # <-- your actual repo ID
    category = "Announcements"                     # <-- must match the discussion category name
    categoryID = "DIC_kwDOPN9Pm84CtEx1"      # <-- your actual category ID
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "light"
    lang = "en"
    loading = "lazy"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    name = "Search"
    url = "search/"
    weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]
